# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoiGas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GoiGas

  # target 'GoiGas-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # target 'GoiGasTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

# target 'GoiGas-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for GoiGas-tvOS

#   target 'GoiGas-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
